# Loading Module 1 | EnderNightLord |

import time
print('(<->     )')
time.sleep(2)
print('( <->    )')
time.sleep(2)
print('(  <->   )')
time.sleep(2)
print('(   <->  )')
time.sleep(2)
print('(    <-> )')
time.sleep(2)
print('(     <->)')
time.sleep(2)
print('(    <-> )')
time.sleep(2)
print('(   <->  )')
time.sleep(2)
print('(  <->   )')
time.sleep(2)
print('( <->    )')
time.sleep(2)
print('(<->     )')
